<?php
/**
 * Copyright © 2015 sendboxcommerce. All rights reserved.
 */
?>
<?php
/**
 * {{controller}} {{action}} template
 *
 * @var $block \Sendbox\Shipment\Block\Adminhtml\GetquotesAdmin\Index
 */




?>
<center>
<?php

if($block->has_weight())
{
if(is_array($block->getQuotes()))
{
?>
	<h2>Choose Carrier</h2><form method="post" action="<?php echo $block->getShipmentPostUrl();?>">
	<div class="origin_name">
		<label for="email">Carrier Rates:</label>
		<select name="selected_courier_id" >
			<?php
			$rates=$block->getQuotes();

			foreach ($rates as $rate) {
			
			?>
			 <option value="<?php echo $rate->id; ?>" ><?php echo $rate->courier->name;?> - ₦<?php echo $rate->fee;?></option>
			<?php
			}
			?>
		</select>
	</div>
	
	<div><input name="form_key" type="hidden" value="<?php echo $block->getFormKey(); ?>" /></div>
	<div><input name="fee" type="hidden" value="<?php echo $rate->fee; ?>" /></div>
	<div> <input type="hidden" value="<?php echo $block->getOrderId(); ?>" name="order_id"/></div>
	<div >
	<br/>
		<button name="submit" class="action- scalable primary" type="submit">Post Shipment</button>
		
	</div>
</form>
<?php }else{
	echo '<div class="message message-error">'.var_dump($block->getQuotes()).'</div>';
	}

  }else
  {
  	echo '<div class="message message-error">Some items do not have weight, please update their weight in Catalog->Products to get quotes</div>';
  }
	?>
</center>